# Generated by Django 5.2.17 on 2026-09-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('units', models.DecimalField(decimal_places=2, default=3, max_digits=4)),
                ('passing_average', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('class_standing_share', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('major_exam_share', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('prelim_exam_weight', models.DecimalField(decimal_places=2, default=33.33, max_digits=5)),
                ('midterm_exam_weight', models.DecimalField(decimal_places=2, default=33.33, max_digits=5)),
                ('final_exam_weight', models.DecimalField(decimal_places=2, default=33.33, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CLASS_STANDING', 'Class Standing'), ('MAJOR_EXAM', 'Major Examination')], max_length=30)),
                ('grading_period', models.CharField(blank=True, choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('highest_possible_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='subjects.subject')),
            ],
        ),
    ]
