# Generated by Django 5.2.17 on 2026-09-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_standing_share',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='final_exam_weight',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='major_exam_share',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='midterm_exam_weight',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='prelim_exam_weight',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_standing_percent_share',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='major_exam_percent_share',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.CreateModel(
            name='ClassStandingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('highest_possible_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('grading_period', models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final')], max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_standing_assessments', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='MajorExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_period', models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('highest_possible_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, default=33.33, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_exams', to='subjects.subject')),
            ],
            options={
                'unique_together': {('subject', 'grading_period')},
            },
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
