# Generated by Django 6.1.1 on 2026-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_class_standing_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]