# Generated by Django 6.1.1 on 2026-09-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_last_viewed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexam',
            name='weight',
        ),
    ]